import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import React from "react";
import Link from "next/link";

const Home: NextPage = () => {

  const { data: sessionData } = useSession();

  console.log("session", sessionData)

  return (
    <>
      <Head>
        <title>Ones</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-gray-900">

        <AuthShowcase />

      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {

  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>

      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>

      { sessionData?.user.roles.includes('admin') &&
        <Link href="/admin">
          <button className="bg-white/10 px-10 py-3 font-semibold text-white transition hover:bg-white/20 rounded-full">
            Admin Page
          </button>
        </Link>
      }

    </div>
  );
};
